
kind: Service
apiVersion: v1
metadata:
  name: webling
  namespace: default
  labels:
    app: webtester
spec:
  type: LoadBalancer
  selector:
    app: webtester
  ports:
  - name: web
    protocol: TCP
    port: 8000
    targetPort: web

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtest
  namespace: default
  labels:
    app: webtester
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webtester
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: webtester
    spec:
      containers:
      - name: testing
        image: zepp/fintest:latest
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "8000"
        ports:
        - name: web
          containerPort: 8000
        volumeMounts:
        - name: config
          mountPath: /etc/wurst/
      volumes:
      - name: config
        configMap:
          name: webtestmap

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: webtestmap
data:
  config.file: |-
    testyo
